export const CREATE_USER = 'CREATE_USER'
export const CREATE_STORE = 'CREATE_STORE'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const GET_STORES = 'GET_STORES'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const GET_LIST = 'GET_LIST'
